### Q1. What are the benefits of the built-in array package, if any?

    -Arrays represent multiple data items of the same type using a single name.
    -In arrays, the elements can be accessed randomly by using the index number.
    -Arrays allocate memory in contiguous memory locations for all its elements. Hence there is no chance of extra memory being allocated in case of arrays. This avoids memory overflow or shortage of memory in arrays.

### Q2. What are some of the array package's limitations

    The number of elements to be stored in an array should be known in advance.

    An array is a static structure (which means the array is of fixed size). Once declared the size of the array cannot be modified. The memory which is allocated to it cannot be increased or decreased.

    Insertion and deletion are quite difficult in an array as the elements are stored in consecutive memory locations and the shifting operation is costly.

    Allocating more memory than the requirement leads to wastage of memory space and less allocation of memory also leads to a problem.

### Q3. Describe the main differences between the array and numpy packages.

    The array package doesn't provide any help with numerical calculation with the items insdie it in number form while NumPy give you a wide variety of numerical operations

    An array is a single dimensional entity which hold the numerical data, while numpy can have more than 1 dimension.

    In case of array, item can be accessed by its index position and it is easy task while in numpy item is accessed by its column and row index, which makes it slightly time taking. Same goes with appending operation.

    In case of array we do not form a tabular structure, while in numpy it forms a tabular structure

### Q4. Explain the distinctions between the empty, ones, and zeros functions.

    empty function: An empty function is a function that does not contain any statement within its body. If you try to write a function definition without any statement in python ,it will return an error. To avoid this, we use pass statement. pass is a special statement in Python that does nothing. It only works as a dummy statement

    ones: This function returns a new array of given shape and data type, where the element’s value is 1.

    zeros: This function returns a new array of given shape and data type, where the element’s value is 0

### Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

    Its function is to execute the function over each coordinate and the resulting array. The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis.

### Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

    If any scaler value such as integer is added to the numpy array then all the elements inside the array will add that value in it.

    Example

In [3]:
import numpy as np

a=np.arange(9).reshape(3,3)
print(a)
print()
print(a+1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

    It will do the operation as per operators. Like if we use + operand it will update the current array by adding and when we use '*', it will update by multiplying.

In [5]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
a+=1

In [7]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
a*=2

In [9]:
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

    Yes it is possible that we can include a string of fixed length in numpy array. The dtype of any numpy array containing string values is the maximum length of any string present in the array. Once set, it will only be able to store new string having length not more than the maximum length at the time of the creation. If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length accept upto those values which are under the limit

In [10]:
# Creating a array cotain sring
srr = np.array(["Krishna", "Balaram", "Ram", "Lakhsman"])

# showing the string array
srr

array(['Krishna', 'Balaram', 'Ram', 'Lakhsman'], dtype='<U8')

In [11]:
# Now max cahr length is 8 
# Adding another name longer than 8 charecter
srr[0] = "Mahabharata" # Replacing Krishna.

srr

array(['Mahabhar', 'Balaram', 'Ram', 'Lakhsman'], dtype='<U8')

    From above replace we can see the string take only 8 cahr from replaceing word

### Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

    It works on standerd math concept like matrix addition and matrix multiplication.

In [12]:
# Creating two array

arr1 = np.arange(10).reshape(5,2)
arr2 = np.arange(10).reshape(5,2)

# Showing array
arr1, arr2

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [13]:
# Addition of array
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [14]:
# Multiplication of array
arr1 * arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

### Q10. What is the best way to use a Boolean array to mask another array?

In [15]:
# Creating bool array
boo = np.array([True,True,False,True]) 

# Creating array of integer values
arr = np.array([1,2,3,4])

# Creating mask 
mask = np.ma.masked_where(arr>2, boo)  

# Showing the mask
print(list(mask))

[True, True, masked, masked]


### Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

    Standard deviation can be calculated in amny ways. If wee see the formula of SD, it says

    std= Square Root of [ Summation of [square of (x-mean)/number of observation] ]

    So this can be achive by:

In [17]:
# In term of fast calcualtion numpy library will perform fast
# creating array  
arr = np.arange(10)

print(arr)
# calcualting standerd deviuation
st = np.std(arr)

# Showing standerd deviation
st

[0 1 2 3 4 5 6 7 8 9]


2.8722813232690143

In [18]:
# We can also calculate std by using python statistics function
from statistics import stdev

# Calculating standerd deviation
st = stdev(arr)

# Showing result.
st

3.0

### Q12. What is the dimensionality of a Boolean mask-generated array?

    It will be same as that of the given array.

    Example we have two aray of same dimensions say 1, then the array produced by given array will be of same dimension

In [19]:
y = np.array([True,True,False,True])          
x = np.array([1,2,3,4])         
m = np.ma.masked_where(x>2,y)  
print(list(m))
print()
print('Dimension is',m.ndim)

[True, True, masked, masked]

Dimension is 1
